In [2]:
import numpy as np
np.ones((10,5)).shape

(10, 5)

In [6]:
np.ones((3,4,5),dtype=np.float64).strides

(160, 40, 8)

In [7]:
ints = np.ones(10,dtype = np.uint16)
floats = np.ones(10,dtype=np.float32)
np.issubdtype(ints.dtype,np.integer)

True

In [8]:
np.issubdtype(floats.dtype,np.floating)

True

In [9]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [10]:
np.issubdtype(ints.dtype,np.number)

True

In [6]:
arr = np.arange(10)*100
inds = [7,1,6,2]
arr[inds]

array([700, 100, 600, 200])

In [7]:
arr.take(inds)

array([700, 100, 600, 200])

In [8]:
arr.put(inds,42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [9]:
arr.put(inds,[40,41,42,43])
arr

array([  0,  41,  43, 300, 400, 500,  42,  40, 800, 900])

In [10]:
inds = [2,0,2,1]
arr = np.random.randn(2,4)
arr

array([[ 1.31831839,  0.31603954,  1.27303763,  0.27525613],
       [-0.46009473,  1.84803071, -0.53230473,  0.19050767]])

In [11]:
arr.take(inds,axis=1)

array([[ 1.27303763,  1.31831839,  1.27303763,  0.31603954],
       [-0.53230473, -0.46009473, -0.53230473,  1.84803071]])

In [14]:
arr = np.random.randn(4,3)
arr

array([[-1.8711132 ,  1.56346821,  0.03146425],
       [ 0.02748743,  1.23796426,  1.47314308],
       [-1.0275484 , -1.01834041, -0.73384263],
       [-1.70313632,  0.39205698, -2.41270145]])

In [15]:
row_means = arr.mean(1)
row_means.shape

(4,)

In [16]:
row_means.reshape((4,1))

array([[-0.09206025],
       [ 0.91286492],
       [-0.92657715],
       [-1.24126026]])

In [17]:
demeanded = arr - row_means.reshape((4,1))
demeanded.mean(1)

array([ 9.25185854e-18,  0.00000000e+00,  7.40148683e-17, -7.40148683e-17])

In [18]:
arr - arr.mean(1).reshape((4,1))

array([[-1.77905295,  1.65552846,  0.1235245 ],
       [-0.88537749,  0.32509934,  0.56027815],
       [-0.10097125, -0.09176327,  0.19273452],
       [-0.46187605,  1.63331724, -1.17144119]])

In [20]:
arr = np.zeros((4,4))
arr_3d = arr[:,np.newaxis,:]
arr_3d.shape

(4, 1, 4)

In [22]:
arr_1d = np.random.normal(size=3)
arr_1d[:,np.newaxis]

array([[1.88510879],
       [0.90149311],
       [2.26577912]])

In [23]:
arr_1d[np.newaxis,:]

array([[1.88510879, 0.90149311, 2.26577912]])

In [27]:
arr = np.random.randn(3,4,5)
depth_means = arr.mean(2)
depth_means

array([[ 0.55019761, -0.90052695, -0.03978253,  0.4108993 ],
       [-0.46472974, -0.14041803, -0.03662913,  0.42993301],
       [ 0.287787  ,  0.16075922, -1.42834731,  0.59317346]])

In [28]:
depth_means.shape

(3, 4)

In [30]:
demeaned = arr - depth_means[:,:,np.newaxis]
demeaned.mean(2)

array([[-6.66133815e-17,  4.44089210e-17, -2.22044605e-17,
         0.00000000e+00],
       [ 4.44089210e-17, -7.77156117e-17,  0.00000000e+00,
         1.11022302e-17],
       [-4.44089210e-17, -8.88178420e-17,  2.66453526e-16,
         1.33226763e-16]])

In [1]:
import numpy as np

In [2]:
arr = np.zeros((4,3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [3]:
col = np.array([1.28,-0.42,0.44,1.6])
arr[:] = col[:,np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [4]:
arr[:2] = [[-1.37],[0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])